swagger: '2.0'
info:
  title: TestGen Backend API
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

x-google-backend:
  address: https://testgen-backend-195472357560.us-central1.run.app
  protocol: h2

paths:
  /health:
    get:
      summary: Health check
      responses:
        200:
          description: Service is healthy

  /api/v2/sessions/{proxy+}:
    x-google-backend:
      address: https://testgen-backend-195472357560.us-central1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Session operations
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    post:
      summary: Create session
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success

  /api/v2/requirements/{proxy+}:
    x-google-backend:
      address: https://testgen-backend-195472357560.us-central1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Requirements operations
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    post:
      summary: Create requirement
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success

  /api/v2/test-cases/{proxy+}:
    x-google-backend:
      address: https://testgen-backend-195472357560.us-central1.run.app
      path_translation: APPEND_PATH_TO_ADDRESS
    get:
      summary: Test cases operations
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
    post:
      summary: Create test case
      parameters:
        - name: proxy
          in: path
          required: true
          type: string
      responses:
        200:
          description: Success
